### ISSUE TITLE
Docker Cloud

### ISSUE THREAD

**Issue by madwire** [tutumcloud/ruby-tutum#32]
Now Tutum is in GA aka Docker Cloud, We might need to start thinking of a rename or maybe add in support for docker cloud.

I patched the TutumApi url method to get it working. But it needs some thought and tests.

``` ruby
class TutumApi
  def url(path)
    'https://cloud.docker.com/api/app/v1' + path
  end
end
```

**Comment by jntullo** [comment]
There seem so be a lot of incompatibilities between TutumApi and Docker Cloud API. New keys generated in Docker Cloud do not work with the Tutum API, and the endpoints are not the same. 

Example:
Tutum API for get all regions:
`/api/v1/region/` 
Docker API for get all regions:
`/api/infra/v1/region/` 

That patch won't work because of these endpoint differences. If old Tutum API keys are backwards compatible, then it seems as if this should be upgraded to the Docker Cloud API, and can be done so safely. I'm not sure if that's the case though. Thoughts?

**Comment by jntullo** [comment]
@madwire decided to work on a Docker Cloud API that could use some love https://github.com/jntullo/ruby-docker-cloud

**Comment by madwire** [comment]
@jntullo I would be happy to lend a hand when I can on your project, but it would be good to get an official response from Docker on this.
